### ISSUE TITLE
How do i re-enable an option after it's been disabled

### ISSUE THREAD

**Issue by MMJv3** [hellzerg/optimizer#42] opened 2021-05-31 05:40 UTC
so i disabled feature updates but the option still looks disabled even after restarting

how do I go about re-enabling features if I ever needed to 

https://i.imgur.com/wMJoCfj.png

**Comment by hellzerg** [comment] 2021-05-31 07:38
Have you checked in Windows Settings > Update section if you can to re-enable feature updates?

**Comment by hellzerg** [comment] 2021-05-31 07:40
[https://media.askvg.com/articles/images6/Delayed_Updates_Download_Windows_10.png](url)

**Comment by Megeme21** [comment] 2021-05-31 09:22
I have the same concern as well. It seems you can't re-enable the tweaks once you have disabled it. I tried checking for new updates on windows update settings but it shows an error and the windows security/defender is also disabled as well even though I didn't disable the windows defender, I think it has something to do with the disabled automatic windows update.

**Comment by hellzerg** [comment] 2021-05-31 09:32
That's strange, Disable Automatic Updates do not touch Defender.

**Comment by Megeme21** [comment] 2021-05-31 09:36
Can we undo the changes though? like re-enabling the automatic windows updates

**Comment by hellzerg** [comment] 2021-05-31 09:37
Yes, give me some minutes.

**Comment by hellzerg** [comment] 2021-05-31 09:53
https://github.com/hellzerg/optimizer/raw/master/lab/Optimizer-Test%2342.exe

Try this build, switch ON Disable Automatic Updates and then OFF again. Restart your PC and check the result.

**Comment by Megeme21** [comment] 2021-05-31 12:35
![Capture](https://user-images.githubusercontent.com/85104843/120193685-4756ae00-c24f-11eb-9e16-008dbf568384.PNG)

tried it and the "Some settings are managed by your organization" message is gone now but still getting an error message when checking for updates.

**Comment by hellzerg** [comment] 2021-05-31 14:39
That's just Windows Update mechanism doing nasty stuff. Try Windows Update troubleshooting.

**Comment by MMJv3** [comment] 2021-05-31 17:16
i just want to disable feature updates that's all

**Comment by MMJv3** [comment] 2021-05-31 17:17
The paused updates was from me from way earlier

https://i.imgur.com/HCvqrTK.png
https://i.imgur.com/jgVO02q.png

**Comment by hellzerg** [comment] 2021-05-31 18:35
Okay, just use the Disable Feature Updates toggle.

**Comment by Megeme21** [comment] 2021-06-01 05:46
> That's just Windows Update mechanism doing nasty stuff. Try Windows Update troubleshooting.

so I found a fix regarding the error 0x80080005 on the windows update. It seems that the error was caused by deleted registry values of wuauserv.

**Comment by Megeme21** [comment] 2021-06-01 06:52
> That's just Windows Update mechanism doing nasty stuff. Try Windows Update troubleshooting.

so I found a fix for the error 0x80080005 on the windows update. It seems that the error was caused by deleted registry values of wuauserv. Windows Update troubleshooting didn't work for me.

**Comment by hellzerg** [comment] 2021-06-01 06:52
Okay, I didn't touch any wuauserv key. I just checked it.

**Closed** 2021-06-02 12:44 UTC
