### ISSUE TITLE
Optimizer wont  open

### ISSUE THREAD

**Issue by DingyMachoMan** [hellzerg/optimizer#430] opened 2023-11-22 16:18 UTC
everytime i open it its checking for requirements  and then it  just closes and nothing else

**Comment by hellzerg** [comment] 2023-11-22 17:28
@DingyMachoMan 
I need logs from C:\ProgramData\optimizer\optimizer.log
as well as from event viewer

**Comment by DingyMachoMan** [comment] 2023-11-26 15:43
> @DingyMachoMan I need logs from C:\ProgramData\optimizer\optimizer.log as well as from event viewer

how do i get to  that  i cant find it

**Comment by hellzerg** [comment] 2023-12-22 11:57
@DingyMachoMan Try deleting the C:\ProgramData\Optimizer whole folder

**Comment by DingyMachoMan** [comment] 2023-12-22 14:16
@hellzerg done do i just redownload now or what?

**Comment by hellzerg** [comment] 2023-12-22 14:35
@DingyMachoMan you should be fine running the app

**Comment by DingyMachoMan** [comment] 2023-12-22 14:49
@hellzerg now  it just says  its already running in the background  when i re install it

**Comment by DingyMachoMan** [comment] 2023-12-22 14:51
@hellzerg and when i open with administrator it just says checking forr requirements then doesnt open same  problem

**Comment by hellzerg** [comment] 2023-12-22 15:24
@DingyMachoMan Did you try latest version? Also check if it is running in task manager.

**Comment by DingyMachoMan** [comment] 2023-12-22 15:38
@hellzerg i got the latest version and it wasnt running in task master

**Comment by hellzerg** [comment] 2023-12-22 18:39
@DingyMachoMan So did it open?

**Comment by DingyMachoMan** [comment] 2023-12-22 19:08
@hellzerg nope  nothin  changed

**Comment by hellzerg** [comment] 2023-12-22 19:16
I need the logs @DingyMachoMan

**Comment by DingyMachoMan** [comment] 2023-12-23 13:06
@hellzerg wherre  do i get that

**Comment by MrDromp** [comment] 2023-12-26 19:47
Same problem for me here. My workaround was, to try [Releases](https://github.com/hellzerg/optimizer/releases) that's working, for me 15.4. I started 15.4 once, closed it and now the newest Version 16.3 is working too.

**Comment by B-l-a-z-e** [comment] 2023-12-27 04:16
umh i cant open it says its already running in the background

**Comment by hellzerg** [comment] 2023-12-29 19:00
@MrDromp Can you try the latest v16.4 and report if the issue is solved?

**Comment by DingyMachoMan** [comment] 2023-12-30 16:08
> Same problem for me here. My workaround was, to try the last [Release](https://github.com/hellzerg/optimizer/releases) that's working, for me 15.4. I started 15.4 once, closed it and now the newest Version 16.3 is working too.

@MrDromp this is my  first time tryna get it tho

**Comment by DingyMachoMan** [comment] 2023-12-30 16:09
@hellzerg version 16.4  works thanks man

**Closed** 2024-01-02 09:56 UTC
